#!/usr/bin/python

import os
import sys
from xml.dom import minidom

dbname = sys.argv[1]
if len(sys.argv) == 3:
	filterfile = sys.argv[2]
#print dbname
xmlfile = dbname + '.xml'
csvfile = dbname + '-csv.xml'

# fields fileter
try:
	f = open(filterfile)
	filter = set(f.read().splitlines())
	f.close()
	#print 'filter: '
	#print filter
except NameError:
	filter = None

# Map eSM names to view names
csvdata = minidom.parse(csvfile)
fields = csvdata.getElementsByTagName('ViewAttr')
viewNameMap = dict()
for field in fields:
	eSM_name = field.getAttribute('Link-SvcAttr')
	view_name = field.getAttribute('vatName')
	viewNameMap[eSM_name] = view_name

### functions for parsing DATA_ITEMs ###
"""
	parse DATA_ITEMs to the following format:
	itemlist = {
		esm_name : {
			'view_name' : view_name,
			'type' : type,
			'type_description' : type_desc,
			'required' : 'Required|Optional',
			'allow_by_esm' : 'y|n',
		},
		...
	}
"""
def get_type_desc(xml_item, type):
	if type == 'counter':
		type_desc = 'Counter'
	elif type == 'counter range':
		range_constraint = item.getElementsByTagName('RangeConstraint')
		if len(range_constraint) > 1:
			print >> sys.stderr, type, name
		range_constraint = range_constraint[0]
		maxValue = range_constraint.getAttribute('maxValue')
		minValue = range_constraint.getAttribute('minValue')
		type_desc = 'Counter(' + minValue + ',' + maxValue + ')'
	elif type == 'digit_string':
		length_constraint = item.getElementsByTagName('LengthConstraint')
		if len(length_constraint) != 1:
			print >> sys.stderr, type, name
			type_desc = 'digital string'
		else:
			length_constraint = length_constraint[0]
			maxLen = length_constraint.getAttribute('maxLength')
			minLen = length_constraint.getAttribute('minLength')
			type_desc = minLen + '-' + maxLen + ' digital string'
	elif type == 'string':
		length_constraint = item.getElementsByTagName('LengthConstraint')
		if len(length_constraint) != 1:
			print >> sys.stderr, type, name
			type_desc = 'string'
		else:
			length_constraint = length_constraint[0]
			maxLen = length_constraint.getAttribute('maxLength')
			minLen = length_constraint.getAttribute('minLength')
			type_desc = minLen + '-' + maxLen + ' string'
	elif type == 'enum' or type == 'enum symbolic':
		enum_values = item.getElementsByTagName('EnumValue')
		type_desc = 'Enumeration:'
		for enumValue in enum_values:
			type_desc += '\n' + enumValue.getAttribute('user_mnemonic')
	elif type == 'flag':
		type_desc = 'Flag(Y/N)'
	elif type == 'hex_value':
		type_desc = type
	else:
		type_desc = type
		print >> sys.stderr, 'unknown type: ' + type

	return type_desc

def data_item(xml_item):
	name = xml_item.getAttribute('NAME')
	view_name = viewNameMap[name]
	type = xml_item.getAttribute('TYPE')
	type_desc = get_type_desc(xml_item, type)

	required = item.getAttribute('IS_REQUIRED')
	if required == 'true':
		required = "Required"
	else:
		required = "Optional"

	dist_attr = item.getAttribute('DISTRIBUTION')
	if dist_attr == "dist_init_only":
		allow_by_esm = 'n'
	else:	# allow update
		allow_by_esm = 'y'

	return {
		'view_name' : view_name,
		'type' : type,
		'type_description' : type_desc,
		'required' : required,
		'allow_by_esm' : allow_by_esm,
	}

xmldata = minidom.parse(xmlfile)
xml_item_list = xmldata.getElementsByTagName('DATA_ITEM')
itemlist = []
for item in xml_item_list:
	name = item.getAttribute('NAME')
	if filter and name not in filter:
		continue
	# skip mashed keys
	if item.getAttribute('AGGRTYPE') == 'mashedkey':
		continue
	itemlist.append(data_item(item))

### functions for converting to html ###
def convert_eol_to_html(sin):
	excel_incell_br = '<br style="mso-data-placement:same-cell;" />'
	return sin.replace('\n', excel_incell_br)

def dict_to_html_tr(item, header):
	tr = ''
	for field in header:
		tr += '<td>' + convert_eol_to_html(item[field]) + '</td> '
	return '<tr> ' + tr + '</tr>\n'

def list_to_html_table(list, header):
	tb = ''
	for item in list:
		tb += dict_to_html_tr(item, header)
	return '<table>\n' + tb + '</table>\n'

# Write to html table
tbheader = ['view_name', 'type_description', 'required']
print list_to_html_table(itemlist, tbheader)
